# Generated by Django 4.2.2 on 2023-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("date",),
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ("date",), "verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
